package:
  name: eba3
  version: "3.0.0"

source:
  path: .

build:
  number: 0
  noarch: generic

requirements:
  build:
    - make
  host:
    - perl >=5.32.1
  run:
    - perl >=5.32.1

test:
  commands:
    - EBA.pl -h

about:
  home: https://bioinformaticsonline.com
  license: Academic-Use-Only
  summary: "Evolutionary Breakpoints Analyser (EBA) Tool"
  description: |
    Evolutionary Breakpoints Analyser (EBA) is a comprehensive bioinformatics 
    tool designed for precise detection of chromosomal breakpoint regions in 
    assembled chromosome or genome sequences. It identifies and classifies 
    genomic rearrangement breakpoints and assigns them to phylogenetic nodes.
  doc_url: https://bioinformaticsonline.com
  dev_url: https://github.com/pranjalpruthi/eba3

extra:
  recipe-maintainers:
    - pranjalpruthi
    - jitendralab
